#include "../include/menuHints.h"

char *menuHints[] = {
    "",
    "change input 0",
    "change input 1",
    "change input 2",
    "change input 3",
    "change input 4",
    "change input 5",
    "change input 6",
    "change input 7",
    "change input 8",
    "change input 9",
    "change input A",
    "change input B",
    "change input C",
    "change input D",
    "change input E",
    "change input F",
    "move menu",
    "change piece rotation",
    "Enter/exit selection mode\nC to Copy\nV to paste\nX to Cut\nBACKSPACE to delete",
    "Hide/show bottom menu",
    "Hide/show left menu",
    "Save",
    "Save and exit",
    "Exit",
    "Play/pause ticks",
    "Reset tick",
    "Foward one tick",
    "select input one",
    "select input two",
    "select input three",
    "select input four",
    "select AND gate",
    "select NAND gate",
    "select semi-curved double wire (left)",
    "select double wire",
    "select curved double wire",
    "select start signal",
    "select input five",
    "select input six",
    "select input seven",
    "select input eight",
    "select OR gate",
    "select NOR gate",
    "select semi-curved double wire (right)",
    "select wire",
    "select curved wire",
    "select data latch (off)",
    "select input nine",
    "select input ten",
    "select input eleven",
    "select input twelve",
    "select XOR gate",
    "select NXOR gate",
    "select T double wire",
    "select crossed wires",
    "select double corner wire",
    "select data latch (on)",
    "select input thirteen",
    "select input fourteen",
    "select input fifteen",
    "select input sixteen",
    "select BUFFER gate",
    "select NOT gate",
    "select multi-output wire (left and right)",
    "select multi-output wire (left and top)",
    "select multi-output wire (right and top)",
    "select multi-output wire (full)"
};
